### ISSUE TITLE
[Help] Use Web-UI on VM and port to local-host

### ISSUE THREAD

**Issue by SidPad03** [aiverify-foundation/moonshot#279]
Hi Moonshot community, 

My company is working on a project related to the safety and efficacy of LLM's and we want to use your tool for red teaming.

I would like some help with running the web-UI version of moonshot from a VM on my local machine. All my development work in my company is done on a server running Ubuntu, and when I run the command `python -m moonshot web`, I am getting many errors (listed below). I couldn't figure out the issue on why these errors are appearing on my machine. 

I would like to also kindly request knowledge from anyone that knows how to access the localhost of the moonshot user-interface from my virtual machine on my local machine. 

```bash
(moonshot) vagrant@vm19:~/code/moonshot$ python -m moonshot web

> moonshot-ui@0.1.0 start /home/vagrant/code/moonshot/moonshot-ui
> next start

[2024-07-30 04:21:42,226] [INFO] [root]: Logging is configured.
[2024-07-30 04:21:42,226] [INFO] [root]: Environment: DEV
[2024-07-30 04:21:42,227] [WARNING] [moonshot.integrations.web_api.app]: CORS is disabled
[2024-07-30 04:21:42,317] [DEBUG] [asyncio]: Using selector: EpollSelector
[2024-07-30 04:21:42,335] [INFO] [uvicorn.error]: Started server process [31021]
[2024-07-30 04:21:42,335] [INFO] [uvicorn.error]: Waiting for application startup.
[2024-07-30 04:21:42,335] [INFO] [uvicorn.error]: Application startup complete.
[2024-07-30 04:21:42,336] [INFO] [uvicorn.error]: Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
/home/vagrant/code/moonshot/moonshot-ui/node_modules/next/dist/compiled/commander/index.js:1
(()=>{var t={81:t=>{"use strict";t.exports=require("child_process")},361:t=>{"use strict";t.exports=require("events")},147:t=>{"use strict";t.exports=require("fs")},17:t=>{"use strict";t.exports=require("path")},282:t=>{"use strict";t.exports=require("process")},161:(t,e,i)=>{const{InvalidArgumentError:n}=i(854);class Argument{constructor(t,e){this.description=e||"";this.variadic=false;this.parseArg=undefined;this.defaultValue=undefined;this.defaultValueDescription=undefined;this.argChoices=undefined;switch(t[0]){case"<":this.required=true;this._name=t.slice(1,-1);break;case"[":this.required=false;this._name=t.slice(1,-1);break;default:this.required=true;this._name=t;break}if(this._name.length>3&&this._name.slice(-3)==="..."){this.variadic=true;this._name=this._name.slice(0,-3)}}name(){return this._name}_concatValue(t,e){if(e===this.defaultValue||!Array.isArray(e)){return[t]}return e.concat(t)}default(t,e){this.defa

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.mod.require (/home/vagrant/code/moonshot/moonshot-ui/node_modules/next/dist/server/require-hook.js:65:28)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vagrant/code/moonshot/moonshot-ui/node_modules/next/dist/bin/next:7:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! moonshot-ui@0.1.0 start: `next start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moonshot-ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2024-07-30T04_21_42_600Z-debug.log
```

**Comment by imda-amdlahir** [comment]
Hi @SidPad03 

Are you using node.js version >20.11.1 ? 

If the `next start` issue is resolved, UI should run on port 3000.
On your hypervisor, create a port forwarding rule - `host ip` is your host machine IP address (use the loopback address 127.0.0.1), and the `host port` is a port on your host machine that you want to forward (eg: 4000). 
Set `guest ip` to the ip address that's assigned to your vm and `guest port` must be the port that UI is on (3000).

If the port forwarding is set correctly, you should be able to access the UI from your browser on your host machine using the url http://localhost:4000

**Comment by SidPad03** [comment]
Hi @imda-amdlahir,

I really appreciate your response. 

After reinstalling node.js on my machine, the `next start` issue has been resolved. I am running into a new issue when generating the static pages. 

```bash 
   Generating static pages (2/25)  [=   ]TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10041)
    at async u (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10208) {
  digest: '167067439',
  [cause]: Error: connect ECONNREFUSED 0.0.0.0:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 5000
  }
}
TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10041)
    at async u (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10208) {
  digest: '167067439',
  [cause]: Error: connect ECONNREFUSED 0.0.0.0:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 5000
  }
}
TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10041)
    at async u (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10208) {
  digest: '167067439',
  [cause]: Error: connect ECONNREFUSED 0.0.0.0:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 5000
  }
}

Error occurred prerendering page "/benchmarking/cookbooks". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10041)
    at async u (/home/vagrant/moonshot/moonshot-ui/.next/server/app/benchmarking/cookbooks/page.js:1:10208)
 ✓ Generating static pages (25/25)

> Export encountered errors on following paths:
	/benchmarking/cookbooks/page: /benchmarking/cookbooks
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/vagrant/moonshot/moonshot/__main__.py", line 241, in <module>
    main()
  File "/home/vagrant/moonshot/moonshot/__main__.py", line 201, in main
    moonshot_ui_installation()
  File "/home/vagrant/moonshot/moonshot/__main__.py", line 141, in moonshot_ui_installation
    run_subprocess(["npm", "run", "build"], check=True)
  File "/home/vagrant/moonshot/moonshot/__main__.py", line 28, in run_subprocess
    return subprocess.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/moonshot/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1.
```

**Comment by imda-amdlahir** [comment]
Hi @SidPad03 

This is probably the same issue as https://github.com/aiverify-foundation/moonshot/issues/268#issuecomment-2257557312
The fix for that should be merged and released soon.
Meanwhile, you can try this:

- go into `moonshot-ui` folder
- run `rm -rf .next`
- make this one-liner code chage - https://github.com/aiverify-foundation/moonshot-ui/pull/28/files
- rerun the start up command `python -m moonshot web`

@imda-benedictlee @imda-normanchia fyi

**Comment by SidPad03** [comment]
Hi @imda-amdlahir,

Thank you for the response, it works now. I've gotten it up and running and also got ip forwarding to work as well. 

If anyone is facing a similar problem as me, here are the steps to the solution:

```bash
sudo iptables -L -v # Check the existing rules
sudo nano /etc/sysctl.conf # Enter the sysctl.conf file
  -> # Uncomment `net.ipv4.ip_forward=1` line
sudo sysctl -p # Apply changes

# Adding the IP tables rule (replace GUEST_IP with your IP)
sudo iptables -t nat -A PREROUTING -p tcp --dport 4000 -j DNAT --to-destination GUEST_IP:3000
sudo iptables -t nat -A POSTROUTING -p tcp -d GUEST_IP --dport 3000 -j MASQUERADE

# Save the rules (screen will pop up enter yes)
sudo apt-get install iptables-persistent
sudo netfilter-persistent save

# Check if the rules have been added in correctly
sudo iptables -t nat -L -v


# Go to http://localhost:4000/redteaming on local machine (You may need to change "localhost" to IP of VM)
```
