### ISSUE TITLE
npm not found when installing moonshot-ui requirements

### ISSUE THREAD

**Issue by fcanogab** [aiverify-foundation/moonshot#282]
I got this error while installing moonshot-ui requirements:

2024-08-01 14:36:57,127 [INFO][__main__.py::moonshot_ui_installation(137)] Installing requirements for moonshot-ui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/sources/moonshot/moonshot/__main__.py", line 241, in <module>
    main()
  File "/home/user/sources/moonshot/moonshot/__main__.py", line 201, in main
    moonshot_ui_installation()
  File "/home/user/sources/moonshot/moonshot/__main__.py", line 140, in moonshot_ui_installation
    run_subprocess(["npm", "install"], check=True)
  File "/home/user/sources/moonshot/moonshot/__main__.py", line 28, in run_subprocess
    return subprocess.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

**Comment by SidPad03** [comment]
Hi @fcanogab,

Did you install node or npm?

These are the instructions for linux, but you can find other installation instructions here: https://nodejs.org/en/download/package-manager

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
nvm install 20
node -v #  Should print 20.11.1
npm -v # Should print 10.8.1
```

**Comment by fcanogab** [comment]
@SidPad03, I did this and it works now. I have seen it is documented as a requirement. I didn't see this line the first time, sorry.
Just for other people that reached here: if you have already done the installation, you can delete the directory moonshot-ui and re-run this after installing nvm and node.
