### ISSUE TITLE
Issue when building the application

### ISSUE THREAD

**Issue by hingsoon** [aiverify-foundation/moonshot#312]
Python 3.11.9

Getting the following error when trying to install with the statement below

python -m moonshot -i moonshot-data -i moonshot-ui

Below are the errors:-

--for tensorflow-hub==0.16.1

Collecting tensorflow-hub==0.16.1 (from -r requirements.txt (line 163))
  Using cached tensorflow_hub-0.16.1-py2.py3-none-any.whl.metadata (1.3 kB)
ERROR: Ignored the following versions that require a different python version: 0.28.0 Requires-Python >=3.7, <3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11

-- for tensorflow-io-gcs-filesystem==0.37.1

ERROR: Could not find a version that satisfies the requirement tensorflow-io-gcs-filesystem==0.37.1 (from versions: 0.29.0, 0.30.0, 0.31.0)
ERROR: No matching distribution found for tensorflow-io-gcs-filesystem==0.37.1

**Comment by miyamaya9** [comment]
Hi @hingsoon At the moment, there seems to be no tensorflow-io-gcs-filesystem wheel for Windows beyond a certain version. We will be updating our troubleshoot documentation in upcoming release, meanwhile can we advice you to try the following:

In the directory where you installed moonshot-data, change the version of tensorflow-io-gcs-filesystem in moonshot-data/requirements.txt to 0.31.0.
Install the requirements of moonshot-data again: 

pip` install -r moonshot-data/requirements.txt.

The issue should be resolved.

**Comment by leonyap27** [comment]
> Hi @hingsoon At the moment, there seems to be no tensorflow-io-gcs-filesystem wheel for Windows beyond a certain version. We will be updating our troubleshoot documentation in upcoming release, meanwhile can we advice you to try the following:
> 
> In the directory where you installed moonshot-data, change the version of tensorflow-io-gcs-filesystem in moonshot-data/requirements.txt to 0.31.0. Install the requirements of moonshot-data again:
> 
> pip` install -r moonshot-data/requirements.txt.
> 
> The issue should be resolved.
@miyamaya9 it prompt the error below:
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiverify-moonshot 0.4.6 requires datasets==2.20.0, but you have datasets 2.14.4 which is incompatible.**
Successfully installed absl-py-2.1.0 accelerate-0.33.0 aiohappyeyeballs-2.3.5 aiohttp-3.10.0 aiometer-0.5.0 anthropic-0.32.0 anytree-2.12.1 astunparse-1.6.3 beautifulsoup4-4.12.3 bert-score-0.3.13 bioc-2.1 blis-0.7.11 boto3-1.34.156 botocore-1.34.156 catalogue-2.0.10 cloudpathlib-0.18.1 coloredlogs-15.0.1 confection-0.1.5 conllu-4.5.3 contourpy-1.2.1 cycler-0.12.1 cymem-2.0.8 datasets-2.14.4 deprecated-1.2.14 dill-0.3.7 distro-1.9.0 docopt-0.6.2 editdistance-0.8.1 eval-type-backport-0.2.0 flair-0.14.0 flatbuffers-24.3.25 fonttools-4.53.1 fsspec-2024.6.1 ftfy-6.2.3 gast-0.6.0 gdown-5.2.0 google-pasta-0.2.0 grpcio-1.65.4 h5py-3.11.0 homoglyphs-2.0.4 httpcore-1.0.5 httpx-0.27.0 huggingface-hub-0.24.5 humanfriendly-10.0 idna-3.7 intervaltree-3.1.0 jieba-0.42.1 jiter-0.5.0 jmespath-1.0.1 joblib-1.4.2 jsonlines-4.0.0 keras-3.4.1 kiwisolver-1.4.5 langcodes-3.4.0 langdetect-1.0.9 language-data-1.2.0 language-tool-python-2.8 lemminflect-0.2.3 libclang-18.1.1 lightning-utilities-0.11.6 lru-dict-1.3.0 lxml-5.2.2 marisa-trie-1.2.0 markdown-3.6 matplotlib-3.9.1.post1 ml-dtypes-0.4.0 more-itertools-10.4.0 mpld3-0.5.10 mpmath-1.3.0 multiprocess-0.70.15 murmurhash-1.0.10 namex-0.0.8 networkx-3.3 nltk-3.8.1 nudenet-3.4.2 num2words-0.5.13 onnxruntime-1.18.1 openai-1.38.0 opencv-python-headless-4.10.0.84 openhownet-2.0 opt-einsum-3.3.0 optree-0.12.1 pillow-10.4.0 pinyin-0.4.0 pptree-3.1 preshed-3.0.9 protobuf-4.25.4 psutil-6.0.0 py-readability-metrics-1.4.5 pybind11-2.13.1 pylcs-0.1.1 pysocks-1.7.1 pytorch-revgrad-0.2.0 regex-2024.7.24 rouge-1.0.1 rouge-score-0.1.2 s3transfer-0.10.2 safetensors-0.4.4 scikit-learn-1.5.1 scipy-1.14.0 segtok-1.5.11 semver-3.0.2 sentence-transformers-3.0.1 sentencepiece-0.2.0 shellingham-1.5.4 smart-open-7.0.4 sortedcontainers-2.4.0 soupsieve-2.5 spacy-3.7.5 spacy-legacy-3.0.12 spacy-loggers-1.0.5 sqlitedict-2.1.0 srsly-2.4.8 sympy-1.13.1 tabulate-0.9.0 tensorboard-2.17.0 tensorboard-data-server-0.7.2 tensorflow-2.17.0 tensorflow-hub-0.16.1 tensorflow-intel-2.17.0 tensorflow-io-gcs-filesystem-0.31.0 termcolor-2.4.0 terminaltables-3.1.10 textattack-0.3.10 tf-keras-2.17.0 thinc-8.2.5 threadpoolctl-3.5.0 together-1.2.5 tokenizers-0.19.1 torch-2.4.0 torchmetrics-1.4.1 torchvision-0.19.0 transformer-smaller-training-vocab-0.4.0 transformers-4.44.0 typer-0.12.3 wasabi-1.1.3 weasel-0.4.1 werkzeug-3.0.3 wheel-0.44.0 wikipedia-api-0.6.0 word2number-1.1 wrapt-1.16.0 xgboost-2.1.1 yarl-1.9.4

**Comment by tinygpt** [comment]
Hi team, I'm hitting the same error on my iMac. [Python 3.11.10]

Command: 

`python -m moonshot -i moonshot-data -i moonshot-ui`


Error message:

#Collecting tensorflow-io-gcs-filesystem~=0.37.1 (from -r requirements.txt (line 199))
  Downloading tensorflow_io_gcs_filesystem-0.37.1-cp311-cp311-macosx_10_14_x86_64.whl.metadata (14 kB)
ERROR: Ignored the following versions that require a different python version: 0.28.0 Requires-Python >=3.7, <3.11; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.17.0 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2)
ERROR: No matching distribution found for tensorflow~=2.17.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/team_awesome/anaconda3/envs/moonshot/lib/python3.11/site-packages/moonshot/__main__.py", line 356, in <module>
    main()
  File "/Users/team_awesome/anaconda3/envs/moonshot/lib/python3.11/site-packages/moonshot/__main__.py", line 314, in main
    moonshot_data_installation(args.unattended, args.overwrite)
  File "/Users/team_awesome/anaconda3/envs/moonshot/lib/python3.11/site-packages/moonshot/__main__.py", line 176, in moonshot_data_installation
    run_subprocess(["pip", "install", "-r", "requirements.txt"], check=True)
  File "/Users/team_awesome/anaconda3/envs/moonshot/lib/python3.11/site-packages/moonshot/__main__.py", line 30, in run_subprocess
    return subprocess.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/team_awesome/anaconda3/envs/moonshot/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pip', 'install', '-r', 'requirements.txt']' returned non-zero exit status 1.

**Comment by imda-kelvinkok** [comment]
hi @tinygpt. Sorry for the late reply. Can you try this solution here: https://aiverify-foundation.github.io/moonshot/faq/ (the first issue under **I am having issues installing some Tensorflow Python packages**). We have not tested with Anaconda so it could be that this version of Tensorflow is not available. 

Let us know if it works for you. Thanks!
